# =====================================================
# POSTGRES DEPLOYMENT (runs on db node)
# =====================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        app-role: db
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "students_db"
        ports:
        - containerPort: 5432


      containers:
        - name: api-container
          image: vikashkumardev1996/rest_api_webserver:v2
          ports:
            - containerPort: 5000



---
# =====================================================
# POSTGRES SERVICE
# =====================================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: student-api
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
