apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: student-api

data:
  POSTGRES_DB: studentdb

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: studentdb
            - name: POSTGRES_USER
              value: studentuser
            - name: POSTGRES_PASSWORD
              value: studentpassword
          ports:
           - containerPort: 5432

---

# service

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api

spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  

