name: Self Hosted CI - Ex6.1

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:

  k8s-deploy:
    name: Deployment on K8s
    runs-on: self-hosted


    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Debug – show current directory
        run: pwd

      - name: Debug – list files
        run: ls -la

      - name: Debug – list k8s folder
        run: ls -R k8s || echo "k8s folder not found"


      
      - name: show date
        run: |
          date

      - name: Executer K8s manifest file
        run: |
          pwd            # location of k8s folder
