name: Self Hosted CI - Ex7.2

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:

  Pre-requisite-k8s:
    name: Pre-requiste for k8s
    runs-on: self-hosted


    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Debug – show current directory
        run: pwd

      - name: Debug – list files
        run: ls -la

      - name: Debug – list k8s folder
        run: ls -R k8s || echo "k8s folder not found"


  Create-namespace:
    name: k8s namespace creation
    runs-on: self-hosted
    needs: Pre-requisite-k8s

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Namespace
        run: |
          kubectl apply -f k8s/namespace/
    
  Create-k8s-Deployment:
    name: Executing k8s manifests
    runs-on: self-hosted
    needs: Create-namespace

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4

      - name: Create other reseources and deployments
        run: |
          kubectl apply -f k8s/application/
          kubectl apply -f k8s/database/
          kubectl apply -f k8s/nginx/


  Check-the-API:
    name: Executing k8s manifests
    runs-on: self-hosted
    needs: Create-k8s-Deployment

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4

      - name: Get minikube IP
        run: |
          IP = $(minikube ip)
      
      - name: Do health check
        run: |
          curl http://$IP:30080/health
          
          
